### ISSUE TITLE
How do you change the fallback image to use?

### ISSUE THREAD

**Issue by sdesign75** [ProgressPlanner/local-gravatars#2]
Hi, I'm not a coder but I'd like to use this plugin. There don't seem to be any settings in Wordpress or instructions on how to change the settings, or have I missed them? When I enable this plugin it sets everyones Gravatar to the Gravatar icon. How do I change the fallback image to use?

Many thanks

Alex

**Comment by aristath** [comment]
Hey there!

You can add this code snippet:

```php
add_filter( 'get_local_gravatars_fallback_url', function() {
    return 'https://example.com/image-avatar.png';
});
```
You can use a plugin like https://wordpress.org/plugins/code-snippets/ to add this, and replace the URL in the above example with the one you want for the fallback avatar.
